// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package foodspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FoodServiceClient is the client API for FoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoodServiceClient interface {
	CreatedFood(ctx context.Context, in *CreatedFoodRequest, opts ...grpc.CallOption) (*FoodResponse, error)
	GetFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error)
	GetFoods(ctx context.Context, in *GetFoodsRequest, opts ...grpc.CallOption) (*FoodsResponse, error)
	UpdateFood(ctx context.Context, in *FoodUpdateRequest, opts ...grpc.CallOption) (*FoodResponse, error)
	DeleteFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodDeleteResponse, error)
}

type foodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodServiceClient(cc grpc.ClientConnInterface) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) CreatedFood(ctx context.Context, in *CreatedFoodRequest, opts ...grpc.CallOption) (*FoodResponse, error) {
	out := new(FoodResponse)
	err := c.cc.Invoke(ctx, "/food.FoodService/CreatedFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) GetFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error) {
	out := new(FoodResponse)
	err := c.cc.Invoke(ctx, "/food.FoodService/GetFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) GetFoods(ctx context.Context, in *GetFoodsRequest, opts ...grpc.CallOption) (*FoodsResponse, error) {
	out := new(FoodsResponse)
	err := c.cc.Invoke(ctx, "/food.FoodService/GetFoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) UpdateFood(ctx context.Context, in *FoodUpdateRequest, opts ...grpc.CallOption) (*FoodResponse, error) {
	out := new(FoodResponse)
	err := c.cc.Invoke(ctx, "/food.FoodService/UpdateFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) DeleteFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodDeleteResponse, error) {
	out := new(FoodDeleteResponse)
	err := c.cc.Invoke(ctx, "/food.FoodService/DeleteFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServiceServer is the server API for FoodService service.
// All implementations must embed UnimplementedFoodServiceServer
// for forward compatibility
type FoodServiceServer interface {
	CreatedFood(context.Context, *CreatedFoodRequest) (*FoodResponse, error)
	GetFood(context.Context, *FoodRequest) (*FoodResponse, error)
	GetFoods(context.Context, *GetFoodsRequest) (*FoodsResponse, error)
	UpdateFood(context.Context, *FoodUpdateRequest) (*FoodResponse, error)
	DeleteFood(context.Context, *FoodRequest) (*FoodDeleteResponse, error)
	mustEmbedUnimplementedFoodServiceServer()
}

// UnimplementedFoodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFoodServiceServer struct {
}

func (UnimplementedFoodServiceServer) CreatedFood(context.Context, *CreatedFoodRequest) (*FoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatedFood not implemented")
}
func (UnimplementedFoodServiceServer) GetFood(context.Context, *FoodRequest) (*FoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFood not implemented")
}
func (UnimplementedFoodServiceServer) GetFoods(context.Context, *GetFoodsRequest) (*FoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoods not implemented")
}
func (UnimplementedFoodServiceServer) UpdateFood(context.Context, *FoodUpdateRequest) (*FoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFood not implemented")
}
func (UnimplementedFoodServiceServer) DeleteFood(context.Context, *FoodRequest) (*FoodDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFood not implemented")
}
func (UnimplementedFoodServiceServer) mustEmbedUnimplementedFoodServiceServer() {}

// UnsafeFoodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodServiceServer will
// result in compilation errors.
type UnsafeFoodServiceServer interface {
	mustEmbedUnimplementedFoodServiceServer()
}

func RegisterFoodServiceServer(s grpc.ServiceRegistrar, srv FoodServiceServer) {
	s.RegisterService(&FoodService_ServiceDesc, srv)
}

func _FoodService_CreatedFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatedFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).CreatedFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food.FoodService/CreatedFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).CreatedFood(ctx, req.(*CreatedFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_GetFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food.FoodService/GetFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetFood(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_GetFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).GetFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food.FoodService/GetFoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).GetFoods(ctx, req.(*GetFoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_UpdateFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).UpdateFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food.FoodService/UpdateFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).UpdateFood(ctx, req.(*FoodUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_DeleteFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).DeleteFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food.FoodService/DeleteFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).DeleteFood(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodService_ServiceDesc is the grpc.ServiceDesc for FoodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatedFood",
			Handler:    _FoodService_CreatedFood_Handler,
		},
		{
			MethodName: "GetFood",
			Handler:    _FoodService_GetFood_Handler,
		},
		{
			MethodName: "GetFoods",
			Handler:    _FoodService_GetFoods_Handler,
		},
		{
			MethodName: "UpdateFood",
			Handler:    _FoodService_UpdateFood_Handler,
		},
		{
			MethodName: "DeleteFood",
			Handler:    _FoodService_DeleteFood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food.proto",
}
